# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - master

# pool:
#   vmImage: 'ubuntu-latest'

# steps:

# - script: |
#     cd tests
#     make && ./tester
#   displayName: 'Run unit tests'

variables:
  CIBW_BEFORE_BUILD: pip install pybind11==2.4.3
  CIBW_SKIP: cp27-win*

jobs:
- job: linux
  pool: {vmImage: 'Ubuntu-16.04'}
  steps:
    - task: UsePythonVersion@0
    - bash: |
        # Make sure the header files are in the docker image.
        cp *.h python
        python -m pip install --upgrade pip
        pip install cibuildwheel==0.12.0
        cd python
        cibuildwheel --output-dir wheelhouse .
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'python/wheelhouse'}
- job: macos
  pool: {vmImage: 'macOS-10.13'}
  variables:
    # Support C++11: https://github.com/joerick/cibuildwheel/pull/156
    MACOSX_DEPLOYMENT_TARGET: 10.9
  steps:
    - task: UsePythonVersion@0
    - bash: |
        python -m pip install --upgrade pip
        pip install cibuildwheel==0.12.0
        cd python
        cibuildwheel --output-dir wheelhouse .
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'python/wheelhouse'}
- job: windows
  pool: {vmImage: 'vs2017-win2016'}
  steps:
    - {task: UsePythonVersion@0, inputs: {versionSpec: '2.7', architecture: x86}}
    - {task: UsePythonVersion@0, inputs: {versionSpec: '2.7', architecture: x64}}
    - {task: UsePythonVersion@0, inputs: {versionSpec: '3.5', architecture: x86}}
    - {task: UsePythonVersion@0, inputs: {versionSpec: '3.5', architecture: x64}}
    - {task: UsePythonVersion@0, inputs: {versionSpec: '3.6', architecture: x86}}
    - {task: UsePythonVersion@0, inputs: {versionSpec: '3.6', architecture: x64}}
    - {task: UsePythonVersion@0, inputs: {versionSpec: '3.7', architecture: x86}}
    - {task: UsePythonVersion@0, inputs: {versionSpec: '3.7', architecture: x64}}
    - script: choco install vcpython27 -f -y
      displayName: Install Visual C++ for Python 2.7
    - bash: |
        cp *.h python
        python -m pip install --upgrade pip
        pip install cibuildwheel==0.12.0
        cd python
        cibuildwheel --output-dir wheelhouse .
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'python/wheelhouse'}
